# Generated by Django 6.0 on 2025-12-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Listener Status',
            },
        ),
    ]
